package net.ukr.dreamsicle.dataBase;

public enum ListColumnNameMainTable {
    ID, GROUP_CADET, RANK, SURNAME, NAME, MIDDLE_NAME, FACULTY, DATE, END_SCHOOL_PLACE, WEDDING, LIVE_PLACE,
    BIRTHDAY_PLACE, NATIONALITY, PILINGS, ENROLLED_BY_ORDER, OUTSIDE_THE_COMPETITION, REGISTRATION_NUMBER,
    ENTRANCE_RATING, VIOLATION, POSITIVE, REASON_FOR_DEDUCTION, ORDER_NUMBER, ORDER_DATE, YEAR_OF_THE_SET,
    TRANSFER_TO_SPECIALITY, PHONE, TRANSFER_TO_SPECIALIZATION, TRANSFER_TO_FACULTY
}
